-- Tabela de Contatos para o Projeto FEVEREIRO_NEW
-- Execute este SQL no seu Supabase SQL Editor

create table public.contatos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome_completo text not null,
  sobrenome text,
  email text not null unique,
  telefone text,
  estado text,
  empresa text,
  categoria text,
  observacoes text,
  
  -- Validação de formato de email
  constraint email_format check (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Habilitar RLS
alter table public.contatos enable row level security;

-- Política simples para permitir acesso (ajuste conforme necessário)
create policy "Permitir acesso total para todos" on public.contatos for all using (true) with check (true);

-- Criar índice no email para buscas rápidas (já garantido pelo unique, mas mantendo o índice explícito se preferir)
-- create index idx_contatos_email on public.contatos(email);

-- Comentários para documentação
comment on table public.contatos is 'Tabela de contatos gerenciada pelo agente n8n';
comment on column public.contatos.nome_completo is 'Primeiro nome ou nome completo';
comment on column public.contatos.sobrenome is 'Sobrenome do contato';
comment on column public.contatos.email is 'Email único do contato (validado)';
comment on column public.contatos.telefone is 'Telefone do contato';
comment on column public.contatos.estado is 'Estado (UF) do contato';
comment on column public.contatos.empresa is 'Empresa do contato';
comment on column public.contatos.categoria is 'Categoria (ex: Cliente, Lead, Fornecedor)';
comment on column public.contatos.observacoes is 'Observações adicionais';
